name: neat_periodic_task
description: copy of neat periodic task https://pub.dev/packages/neat_periodic_task
version: 2.0.1+1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  retry: ^3.1.0
  slugid: ^1.1.0
  json_annotation: ^4.0.0
  meta: ^1.3.0
  logging: ^1.0.0
  collection: ^1.15.0
dev_dependencies:
  test: ^1.16.5
  lints: ^2.0.1
  build_runner: ^2.1.11
  build_verify: ^3.1.0
  json_serializable: ^6.5.4
